version: '3.8'
services:
  nuxt-app:
    # Dockerfileの場所
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: yarn run dev
    # ホストOSとコンテナ内でソースコードを共有する
    volumes:
      - ./frontend/src:/workspace
    working_dir: /workspace
    # コンテナ内部の3000を外部から5000でアクセスする
    ports:
      - 9000:3000