version: '3.8'
services:
  nuxt-app:
    # Dockerfileの場所
    build:
      context: ./frontend/docker/nuxt
      dockerfile: Dockerfile
    command: yarn run dev
    # ホストOSとコンテナ内でソースコードを共有する
    volumes:
      - ./frontend/src:/workspace
    working_dir: /workspace
    # コンテナ内部の3000を外部から5000でアクセスする
    ports:
      - 9000:3000
  db:
    image: mysqlapp
    container_name: "mysqlapp"
    build: ./mysql/
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d #初期処理のフォルダ。初回起動のみでおｋ
      - ./mysql/db:/var/lib/mysql #ここにデータ永続化するためのファイルが入る。
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql_dev
      MYSQL_USER: OKAWA
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
  go-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /backend
    # docker-compose run実行時に実行される
    command: go run main.go
    volumes:
      - ./backend:/backend
    ports:
      - "8080:8080"
    depends_on:
      - db